#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

#Metrics related configurations
management.endpoints.web.exposure.include: "*"
management.endpoint.info.enabled: "true"
management.endpoint.metrics.enabled: "true"
management.endpoint.prometheus.enabled: "true"
management.prometheus.metrics.export.enabled: "true"
management.metrics.web.server.auto-time-requests: "true"
management.info.env.enabled: "true"

#opentracing.jaeger.enabled: "true"

spring:
  profiles:
    active: "production"
  jackson:
    default-property-inclusion: "non_null"
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1} # "jdbc:h2:file:~/cellclustering"
    driverClassName: org.h2.Driver
    username: sa
    password:
    exposed: false
  jpa:
    hibernate.ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:create} # "update"
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.enable_lazy_load_no_trans: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2

endpoints:
  health:
    sensitive: "false"

info:
  app:
    name: '@name@'
    description: Microservice chassis app
    version: '@version@'
    legal: "COPYRIGHT Ericsson 2021 -
 The copyright to the computer program(s) herein is the property of
 Ericsson Inc. The programs may be used and/or copied only with written
 permission from Ericsson Inc. or in accordance with the terms and
 conditions stipulated in the agreement/contract under which the
 program(s) have been supplied."

#See more details about pattern layout: https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html
#See more details about logging.pattern.level : https://docs.spring.io/spring-boot/docs/2.5.2/reference/html/features.html#features.logging.custom-log-configuration
#logging.pattern.level: "%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}][%X{userName}]"

#Set the stubrunner credentials:
stubrunner:
  username: ${SELI_ARTIFACTORY_REPO_USER}
  password: ${SELI_ARTIFACTORY_REPO_PASS}

app:
    data:
        directory: "reports/"
        densityFile: 1704211200000
        
client:
  retries:
    apiRetries: 5
    serverErrorWaitMs: 2000
    serverErrorMaxWaitMs: 60000
  auth-refresh-period: ${AUTH_REFRESH_PERIOD:1200}

rapp-sdk:
    bdr:
        enabled: "true"
        #service: ${BDR_SERVICE:http://eric-data-object-storage-mn:9000}
        service: ${BDR_SERVICE:http://localhost:9000}
        bucket: "cellclustering"
        access-key: ${BDR_ACCESSKEY:minioadmin}
        secret-key: ${BDR_SECRETKEY:minioadmin}
    kafka:
        group-prefix: scoping-rapp
        bootstrapServers: ${KAFKA_SERVICE:eric-oss-dmm-kf-op-sz-kafka-bootstrap:9092}
        enabled: false
        autoStart: true
        consumers:
            nrevents:
                group-id: nrevents
                topics: 5g-pm-event-file-transfer-and-processing--enm1
                listener-class: NREventDataRetrieval
        sender:
            events:
                nrtopic: 5g-pm-event-file-transfer-and-processing--enm1
    ncmp:
        enabled: false
        base-path: ${BASE_URL:http://localhost}/ncmp
    dcc:
        enabled: ${DCC_ENABLED:false}
        base-path: ${BASE_URL:http://localhost}/dmm-data-collection-controller
    catalog:
        enabled: false
